general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:
      priority_level_1: []
    parallels:
        priority_level_1: []
    ss_drivetrain:
        priority_level_1: [st_drivetrain_percent]
        default: [st_drivetrain_percent]
    ss_collector:
        priority_level_2: [st_collector_zero]
        priority_level_1: [st_collector_floor_intake, st_collector_extend, st_collector_retract]
        default: []
    ss_hopper:
      priority_level_2: [st_hopper_zero]
      priority_level_1: [st_hopper_home, st_hopper_collect, st_hopper_shoot]
      default: [st_hopper_stop]

  subsystems: [ss_drivetrain, ss_collector, ss_hopper]

  input_booleans: [
    ipb_driver_left_bumper, ipb_driver_right_bumper, ipb_driver_left_trigger, ipb_driver_right_trigger, ipb_operator_left_bumper, ipb_operator_right_bumper, ipb_operator_left_trigger, ipb_operator_right_trigger, ipb_driver_x]

  input_numerics: [
    ipn_driver_left_y, ipn_driver_left_x, ipn_driver_right_y, ipn_driver_right_x,
    ipn_operator_left_y, ipn_operator_left_x, ipn_operator_right_y, ipn_operator_right_x
  ]

  input_vectors: []

  output_numerics: [opn_drivetrain_left, opn_drivetrain_right, opn_collector_roller, opn_hopper]

  output_booleans: [opb_drivetrain_shifter, opb_collector_deploy, opb_hopper_kicker]

log:

global_drivetrain:
  x: ipn_driver_right_x
  y: ipn_driver_left_y
  gear_shift_button: ipb_driver_x

global_collector:
  floor_intake: ipb_driver_left_trigger
  stop: ipb_driver_right_bumper

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values: