general:
  initial_teleop_mode: teleop_mode
  #  initial_teleop_mode: manual_mode

  states:

    sequences:

    parallels:
    ss_collector:
      priority_level_2: [st_collector_zero]
      priority_level_1: [st_collector_intake_floor, st_collector_retract, st_collector_extend]

    ss_drivetrain:
      priority_level_1: []
      default: [st_drivetrain_percent]

  subsystems: [ss_drivetrain, ss_collector]

  input_booleans: [
    ipb_operator_right_bumper, ipb_operator_left_bumper, ipb_driver_left_trigger
  ]

  input_numerics: [
    ipn_driver_left_y,ipn_driver_right_x
  ]

  input_vectors: []

  output_numerics: [opn_drivetrain_right,opn_drivetrain_left,
                    opn_collector_rollers
                   ]

  output_booleans: [opb_drivetrain_gear_shifter, opb_collector_deploy]


global_timing:
  frame_time_threshold_input_service: 80
  frame_time_threshold_logging_service: 80
  frame_time_threshold_output_service: 80
  frame_time_threshold_state_service: 80
  frame_time_threshold_webdashboard_service: 80
  frame_cycle_time_threshold_core_thread: 80
  frame_cycle_time_threshold_info_thread: 80

global_drivetrain:
  x: ipn_driver_right_x
  y: ipn_driver_left_y
  gear_shift: ipb_driver_left_trigger

global_collector:
  floor_intake: ipb_driver_left_trigger
  stop: ipb_driver_right_bumper

log:

global_webdashboard:

  auto_selector:
    origins: []
    destinations: []
    actions: []

  match_values: